/* The following code was generated by JFlex 1.6.0 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>D:/IC-Complier/IC-Compiler/P1/spec.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\13\1\10\2\0\1\7\22\0\1\12\1\60\1\63\2\14"+
    "\1\54\1\61\1\14\1\43\1\44\1\53\1\52\1\51\1\3\1\47"+
    "\1\11\1\2\11\1\1\14\1\50\1\55\1\56\1\57\2\14\32\5"+
    "\1\15\1\64\1\16\1\14\1\4\1\14\1\25\1\33\1\27\1\23"+
    "\1\17\1\36\1\42\1\40\1\26\1\6\1\41\1\30\1\6\1\22"+
    "\1\32\2\6\1\34\1\24\1\21\1\35\1\31\1\37\1\20\2\6"+
    "\1\46\1\62\1\45\1\14\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff91\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\1\11\14\5\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\2\1\1\30\1\31\1\32\1\33\1\31\2\34"+
    "\1\6\1\35\10\5\1\36\11\5\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\4\5\1\52\3\5\1\53\12\5\1\54\1\55\1\56"+
    "\1\57\5\5\1\60\10\5\1\61\3\5\1\62\1\5"+
    "\1\63\1\64\1\5\1\65\1\66\1\5\1\67\1\5"+
    "\1\70\1\71\1\5\1\72\1\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\237\0\u0109\0\u013e"+
    "\0\u0173\0\u01a8\0\237\0\u01dd\0\237\0\237\0\u0212\0\u0247"+
    "\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef"+
    "\0\u0424\0\u0459\0\237\0\237\0\237\0\237\0\237\0\237"+
    "\0\237\0\237\0\237\0\237\0\u048e\0\u04c3\0\u04f8\0\u052d"+
    "\0\u0562\0\u0597\0\237\0\237\0\u05cc\0\237\0\u0601\0\237"+
    "\0\u0636\0\u066b\0\237\0\u06a0\0\u06d5\0\u070a\0\u073f\0\u0774"+
    "\0\u07a9\0\u07de\0\u0813\0\u0173\0\u0848\0\u087d\0\u08b2\0\u08e7"+
    "\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0\0\237\0\237\0\237"+
    "\0\237\0\237\0\237\0\237\0\237\0\237\0\237\0\237"+
    "\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0173\0\u0af9\0\u0b2e\0\u0b63"+
    "\0\u0173\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6"+
    "\0\u0d0b\0\u0d40\0\u0d75\0\u0173\0\u0173\0\u0173\0\u0173\0\u0daa"+
    "\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u0173\0\u0eb3\0\u0ee8\0\u0f1d"+
    "\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u0173\0\u105b\0\u1090"+
    "\0\u10c5\0\u0173\0\u10fa\0\u0173\0\u0173\0\u112f\0\u0173\0\u0173"+
    "\0\u1164\0\u0173\0\u1199\0\u0173\0\u0173\0\u11ce\0\u0173\0\u0173";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\4\1\10\1\11\1\12"+
    "\1\13\1\14\2\13\1\4\1\15\1\16\1\17\1\11"+
    "\1\20\1\21\1\11\1\22\1\11\1\23\1\24\1\25"+
    "\1\26\1\11\1\27\1\30\1\11\1\31\1\32\3\11"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\4\1\54\6\55\2\54\2\55\1\54\47\55"+
    "\1\56\1\57\53\60\1\61\11\60\66\0\2\5\63\0"+
    "\1\5\1\6\63\0\2\10\1\0\3\10\10\0\24\10"+
    "\23\0\2\11\1\0\3\11\10\0\24\11\32\0\1\13"+
    "\65\0\1\62\41\0\1\63\12\0\2\11\1\0\3\11"+
    "\10\0\1\11\1\64\7\11\1\65\12\11\23\0\2\11"+
    "\1\0\3\11\10\0\15\11\1\66\3\11\1\67\2\11"+
    "\23\0\2\11\1\0\3\11\10\0\1\70\15\11\1\71"+
    "\5\11\23\0\2\11\1\0\3\11\10\0\2\11\1\72"+
    "\21\11\23\0\2\11\1\0\3\11\10\0\3\11\1\73"+
    "\13\11\1\74\4\11\23\0\2\11\1\0\3\11\10\0"+
    "\11\11\1\75\1\11\1\76\10\11\23\0\2\11\1\0"+
    "\3\11\10\0\1\77\23\11\23\0\2\11\1\0\3\11"+
    "\10\0\13\11\1\100\10\11\23\0\2\11\1\0\3\11"+
    "\10\0\13\11\1\101\1\11\1\102\6\11\23\0\2\11"+
    "\1\0\3\11\10\0\1\103\23\11\23\0\2\11\1\0"+
    "\3\11\10\0\6\11\1\104\15\11\23\0\2\11\1\0"+
    "\3\11\10\0\21\11\1\105\2\11\100\0\1\106\64\0"+
    "\1\107\64\0\1\110\64\0\1\111\67\0\1\112\65\0"+
    "\1\113\3\0\6\55\2\0\2\55\1\0\47\55\23\0"+
    "\1\114\1\115\40\0\1\116\1\117\11\0\1\120\53\0"+
    "\7\62\1\12\1\13\54\62\1\0\2\11\1\0\3\11"+
    "\10\0\2\11\1\121\21\11\23\0\2\11\1\0\3\11"+
    "\10\0\5\11\1\122\16\11\23\0\2\11\1\0\3\11"+
    "\10\0\16\11\1\123\5\11\23\0\2\11\1\0\3\11"+
    "\10\0\7\11\1\124\14\11\23\0\2\11\1\0\3\11"+
    "\10\0\20\11\1\125\3\11\23\0\2\11\1\0\3\11"+
    "\10\0\11\11\1\126\12\11\23\0\2\11\1\0\3\11"+
    "\10\0\6\11\1\127\6\11\1\130\6\11\23\0\2\11"+
    "\1\0\3\11\10\0\2\11\1\131\21\11\23\0\2\11"+
    "\1\0\3\11\10\0\6\11\1\132\15\11\23\0\2\11"+
    "\1\0\3\11\10\0\3\11\1\133\20\11\23\0\2\11"+
    "\1\0\3\11\10\0\3\11\1\134\20\11\23\0\2\11"+
    "\1\0\3\11\10\0\7\11\1\135\14\11\23\0\2\11"+
    "\1\0\3\11\10\0\13\11\1\136\10\11\23\0\2\11"+
    "\1\0\3\11\10\0\1\137\23\11\23\0\2\11\1\0"+
    "\3\11\10\0\2\11\1\140\21\11\23\0\2\11\1\0"+
    "\3\11\10\0\11\11\1\141\12\11\23\0\2\11\1\0"+
    "\3\11\10\0\7\11\1\142\14\11\23\0\2\11\1\0"+
    "\3\11\10\0\1\143\23\11\23\0\2\11\1\0\3\11"+
    "\10\0\1\144\23\11\23\0\2\11\1\0\3\11\10\0"+
    "\1\145\23\11\23\0\2\11\1\0\3\11\10\0\5\11"+
    "\1\146\16\11\23\0\2\11\1\0\3\11\10\0\11\11"+
    "\1\147\12\11\23\0\2\11\1\0\3\11\10\0\2\11"+
    "\1\150\21\11\23\0\2\11\1\0\3\11\10\0\7\11"+
    "\1\151\14\11\23\0\2\11\1\0\3\11\10\0\5\11"+
    "\1\152\16\11\23\0\2\11\1\0\3\11\10\0\2\11"+
    "\1\153\21\11\23\0\2\11\1\0\3\11\10\0\23\11"+
    "\1\154\23\0\2\11\1\0\3\11\10\0\4\11\1\155"+
    "\17\11\23\0\2\11\1\0\3\11\10\0\11\11\1\156"+
    "\12\11\23\0\2\11\1\0\3\11\10\0\6\11\1\157"+
    "\15\11\23\0\2\11\1\0\3\11\10\0\16\11\1\160"+
    "\5\11\23\0\2\11\1\0\3\11\10\0\5\11\1\161"+
    "\16\11\23\0\2\11\1\0\3\11\10\0\11\11\1\162"+
    "\12\11\23\0\2\11\1\0\3\11\10\0\3\11\1\163"+
    "\20\11\23\0\2\11\1\0\3\11\10\0\7\11\1\164"+
    "\14\11\23\0\2\11\1\0\3\11\10\0\3\11\1\165"+
    "\20\11\23\0\2\11\1\0\3\11\10\0\5\11\1\166"+
    "\16\11\23\0\2\11\1\0\3\11\10\0\7\11\1\167"+
    "\14\11\23\0\2\11\1\0\3\11\10\0\2\11\1\170"+
    "\21\11\23\0\2\11\1\0\3\11\10\0\1\171\23\11"+
    "\23\0\2\11\1\0\3\11\10\0\22\11\1\172\1\11"+
    "\23\0\2\11\1\0\3\11\10\0\15\11\1\173\6\11"+
    "\23\0\2\11\1\0\3\11\10\0\1\174\23\11\23\0"+
    "\2\11\1\0\3\11\10\0\1\175\23\11\23\0\2\11"+
    "\1\0\3\11\10\0\4\11\1\176\17\11\23\0\2\11"+
    "\1\0\3\11\10\0\10\11\1\177\13\11\23\0\2\11"+
    "\1\0\3\11\10\0\23\11\1\200\23\0\2\11\1\0"+
    "\3\11\10\0\3\11\1\201\20\11\23\0\2\11\1\0"+
    "\3\11\10\0\21\11\1\202\2\11\23\0\2\11\1\0"+
    "\3\11\10\0\6\11\1\203\15\11\23\0\2\11\1\0"+
    "\3\11\10\0\3\11\1\204\20\11\23\0\2\11\1\0"+
    "\3\11\10\0\5\11\1\205\16\11\23\0\2\11\1\0"+
    "\3\11\10\0\16\11\1\206\5\11\23\0\2\11\1\0"+
    "\3\11\10\0\3\11\1\207\20\11\23\0\2\11\1\0"+
    "\3\11\10\0\1\210\23\11\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4611];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\4\1\1\11\1\1\2\11"+
    "\14\1\12\11\6\1\2\11\1\1\1\11\1\1\1\11"+
    "\2\1\1\11\22\1\13\11\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	
	private StringBuffer stringBuilder = new StringBuffer(); // will hold string literals
	private int string_line_start;                           // will hold the the beginning of the string location
	private int string_column_start;
	
	/* return new token of type string */
	private Token getStringToken( String value)
	{
		return new Token(sym.STRING_LITERAL, Token.STRING_TAG, value, string_line_start + 1, string_column_start + 1);
	}
	
	private void resetString()
	{
		// reset buffer
		this.stringBuilder.setLength(0);
		// save beginning of the string location
		this.string_line_start = yyline;
		this.string_column_start = yycolumn;
	}
	
	/* return new token of type id (with tag) */
	private Token getToken(int id, String tag)
	{
		return new Token(id, tag, yytext(), yyline + 1, yycolumn + 1);
		
	}
	/* return new token of type id (without tag) 
	   use this method when tag equals value
	*/
	private Token getToken(int id)
	{
		String value = yytext();
		return new Token(id, value, value, yyline + 1, yycolumn + 1);
		
	}
	



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 162) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new LexicalError("Invalid char: "+ yytext() +" line:"+ (yyline+1) + " column: " + (yycolumn+1));
          }
        case 60: break;
        case 2: 
          { try {
									// try to parse the number to Integer (signed int has the same range as IC spec)
									Integer.parseInt(yytext());
									return getToken(sym.INTEGER, Token.INTEGER_TAG);  
									
							} catch (NumberFormatException e) {
								throw new LexicalError("Error: number " + yytext() +" is not an Integer\n");
							}
          }
        case 61: break;
        case 3: 
          { return getToken(sym.MINUS);
          }
        case 62: break;
        case 4: 
          { return getToken(sym.CLASSID, Token.CLASS_TAG);
          }
        case 63: break;
        case 5: 
          { return getToken(sym.ID, Token.ID_TAG);
          }
        case 64: break;
        case 6: 
          { /* skip */
          }
        case 65: break;
        case 7: 
          { return getToken(sym.DIV);
          }
        case 66: break;
        case 8: 
          { return getToken(sym.SQUARELB);
          }
        case 67: break;
        case 9: 
          { return getToken(sym.SQUARERB);
          }
        case 68: break;
        case 10: 
          { return getToken(sym.LP);
          }
        case 69: break;
        case 11: 
          { return getToken(sym.RP);
          }
        case 70: break;
        case 12: 
          { return getToken(sym.CRP);
          }
        case 71: break;
        case 13: 
          { return getToken(sym.CLP);
          }
        case 72: break;
        case 14: 
          { return getToken(sym.DOT);
          }
        case 73: break;
        case 15: 
          { return getToken(sym.SEMCOL);
          }
        case 74: break;
        case 16: 
          { return getToken(sym.COMMA);
          }
        case 75: break;
        case 17: 
          { return getToken(sym.ADD);
          }
        case 76: break;
        case 18: 
          { return getToken(sym.MULT);
          }
        case 77: break;
        case 19: 
          { return getToken(sym.MOD);
          }
        case 78: break;
        case 20: 
          { return getToken(sym.LESSTHAN);
          }
        case 79: break;
        case 21: 
          { return getToken(sym.ASSIGN);
          }
        case 80: break;
        case 22: 
          { return getToken(sym.GREATERTHAN);
          }
        case 81: break;
        case 23: 
          { return getToken(sym.NOT);
          }
        case 82: break;
        case 24: 
          { this.resetString();  // reset buffer and location fields
								yybegin(STRING);     // parse string
          }
        case 83: break;
        case 25: 
          { throw new LexicalError("String literal was not closed properly, line: " + (yyline+1) + " column: " + (yycolumn +1));
          }
        case 84: break;
        case 26: 
          { stringBuilder.append(yytext());
          }
        case 85: break;
        case 27: 
          { yybegin(YYINITIAL); 
                                   return getStringToken(stringBuilder.toString());
          }
        case 86: break;
        case 28: 
          { /* ignore  */
          }
        case 87: break;
        case 29: 
          { yybegin(COMMENT);
          }
        case 88: break;
        case 30: 
          { return getToken(sym.IF);
          }
        case 89: break;
        case 31: 
          { return getToken(sym.LESSTHANEQ);
          }
        case 90: break;
        case 32: 
          { return getToken(sym.EQ);
          }
        case 91: break;
        case 33: 
          { return getToken(sym.GREATERTHANEQ);
          }
        case 92: break;
        case 34: 
          { return getToken(sym.NOTEQ);
          }
        case 93: break;
        case 35: 
          { return getToken(sym.AND);
          }
        case 94: break;
        case 36: 
          { return getToken(sym.OR);
          }
        case 95: break;
        case 37: 
          { stringBuilder.append("\t");
          }
        case 96: break;
        case 38: 
          { stringBuilder.append("\n");
          }
        case 97: break;
        case 39: 
          { stringBuilder.append("\"");
          }
        case 98: break;
        case 40: 
          { stringBuilder.append("\\");
          }
        case 99: break;
        case 41: 
          { /*  comment closed */
									yybegin(YYINITIAL);
          }
        case 100: break;
        case 42: 
          { return getToken(sym.NEW);
          }
        case 101: break;
        case 43: 
          { return getToken(sym.INT);
          }
        case 102: break;
        case 44: 
          { return getToken(sym.ELSE);
          }
        case 103: break;
        case 45: 
          { return getToken(sym.TRUE);
          }
        case 104: break;
        case 46: 
          { return getToken(sym.THIS);
          }
        case 105: break;
        case 47: 
          { return getToken(sym.NULL);
          }
        case 106: break;
        case 48: 
          { return getToken(sym.VOID);
          }
        case 107: break;
        case 49: 
          { return getToken(sym.CLASS);
          }
        case 108: break;
        case 50: 
          { return getToken(sym.BREAK);
          }
        case 109: break;
        case 51: 
          { return getToken(sym.FALSE);
          }
        case 110: break;
        case 52: 
          { return getToken(sym.WHILE);
          }
        case 111: break;
        case 53: 
          { return getToken(sym.STATIC);
          }
        case 112: break;
        case 54: 
          { return getToken(sym.STRING);
          }
        case 113: break;
        case 55: 
          { return getToken(sym.LENGTH);
          }
        case 114: break;
        case 56: 
          { return getToken(sym.RETURN);
          }
        case 115: break;
        case 57: 
          { return getToken(sym.EXTENDS);
          }
        case 116: break;
        case 58: 
          { return getToken(sym.BOOL);
          }
        case 117: break;
        case 59: 
          { return getToken(sym.CONTINUE);
          }
        case 118: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              // string was not closed
									throw new LexicalError("String literal:" + stringBuilder.toString() 
											+ "was not closed\n");
            }
            case 137: break;
            case COMMENT: {
              /* comment was not closed */
									throw new LexicalError("Comment was not closed!\n");
            }
            case 138: break;
            default:
              { 			return getToken(sym.EOF); 
 }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
