
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 41;
  public static final int METHOD_CALL = 51;
  public static final int STRING_LITERAL = 21;
  public static final int MULT = 36;
  public static final int UMINUS = 49;
  public static final int INTEGER = 20;
  public static final int CONTINUE = 15;
  public static final int INT = 7;
  public static final int SEMCOL = 32;
  public static final int MINUS = 35;
  public static final int STATIC = 5;
  public static final int NOT = 47;
  public static final int AND = 45;
  public static final int OR = 46;
  public static final int LESSTHAN = 39;
  public static final int LP = 25;
  public static final int BOOL = 8;
  public static final int COMMA = 33;
  public static final int CLASS = 19;
  public static final int DIV = 37;
  public static final int RP = 26;
  public static final int ASSIGN = 48;
  public static final int IF = 11;
  public static final int THIS = 16;
  public static final int DOT = 31;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int CLASSID = 3;
  public static final int TRUE = 24;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int ADD = 34;
  public static final int NULL = 23;
  public static final int MOD = 38;
  public static final int CLP = 28;
  public static final int BREAK = 14;
  public static final int VOID = 6;
  public static final int EQ = 43;
  public static final int CRP = 27;
  public static final int ELSE = 12;
  public static final int WHILE = 13;
  public static final int LESSTHANEQ = 40;
  public static final int EXTENDS = 4;
  public static final int ARR_ACCESS = 50;
  public static final int STRING = 9;
  public static final int GREATERTHANEQ = 42;
  public static final int FALSE = 22;
  public static final int SQUARELB = 30;
  public static final int LENGTH = 18;
  public static final int SQUARERB = 29;
  public static final int NOTEQ = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CLASSID",
  "EXTENDS",
  "STATIC",
  "VOID",
  "INT",
  "BOOL",
  "STRING",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "CONTINUE",
  "THIS",
  "NEW",
  "LENGTH",
  "CLASS",
  "INTEGER",
  "STRING_LITERAL",
  "FALSE",
  "NULL",
  "TRUE",
  "LP",
  "RP",
  "CRP",
  "CLP",
  "SQUARERB",
  "SQUARELB",
  "DOT",
  "SEMCOL",
  "COMMA",
  "ADD",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "LESSTHAN",
  "LESSTHANEQ",
  "GREATERTHAN",
  "GREATERTHANEQ",
  "EQ",
  "NOTEQ",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "UMINUS",
  "ARR_ACCESS",
  "METHOD_CALL"
  };
}

